//! `compute_body_hash` must reproduce, byte for byte, the hashes the JS
//! implementation wrote into existing archives (`page_meta.body_hash`).
//! `fixtures/body-hash-golden.json` was generated by that JS implementation.
//! Each case stores its input only as UTF-8 hex
//! (`Buffer.from(html).toString('hex')`), not as a JSON string: inputs with
//! lone surrogates serialize to `\ud800`-style escapes that `serde_json`
//! rejects, while their UTF-8 form — U+FFFD, as `Buffer.from` produces it —
//! is exactly the bytes the addon receives.

use nitpicker_html_scan::compute_body_hash;
use serde_json::Value;

fn decode_hex(hex: &str) -> Vec<u8> {
	assert!(hex.len().is_multiple_of(2), "odd-length hex string");
	(0..hex.len())
		.step_by(2)
		.map(|i| u8::from_str_radix(&hex[i..i + 2], 16).expect("valid hex digit pair"))
		.collect()
}

fn encode_hex(bytes: &[u8]) -> String {
	use std::fmt::Write;
	bytes.iter().fold(String::new(), |mut out, byte| {
		write!(out, "{byte:02x}").expect("writing to a String cannot fail");
		out
	})
}

#[test]
fn matches_every_golden_hash_from_the_js_implementation() {
	let golden: Value = serde_json::from_str(include_str!("fixtures/body-hash-golden.json"))
		.expect("golden fixture is valid JSON");
	let cases = golden.as_array().expect("golden fixture is an array");
	assert!(!cases.is_empty(), "golden fixture has no cases");
	for case in cases {
		let name = case["name"].as_str().expect("case has a name");
		let input = decode_hex(case["utf8Hex"].as_str().expect("case has utf8Hex"));
		let expected = case["hash"].as_str().expect("case has a hash");
		assert_eq!(
			encode_hex(&compute_body_hash(&input)),
			expected,
			"case: {name}"
		);
	}
}
