import type { PageDetail } from '@nitpicker/query';

/**
 * Builds a fully-populated demo `PageDetail` for Storybook stories and
 * tests. `PageDetail` carries ~50 metadata fields; defaulting all of them
 * here means a story only needs to override the handful relevant to what
 * it demonstrates.
 * @param overrides - Fields to override on top of the defaults.
 * @returns The demo `PageDetail`.
 * @example
 * const withDedupeCap = buildDemoPageDetail({ isDedupeCapped: true, dedupeCapEventId: 7 });
 */
export function buildDemoPageDetail(overrides?: Partial<PageDetail>): PageDetail {
	const base: PageDetail = {
		url: 'https://example.com/',
		status: 200,
		statusText: 'OK',
		contentType: 'text/html; charset=utf-8',
		contentLength: 12_345,
		isExternal: false,
		isSkipped: false,
		skipReason: null,
		isDedupeCapped: false,
		dedupeCapShapeKey: null,
		dedupeCapEventId: null,
		title: 'Example Page',
		description: 'An example page for demos.',
		keywords: null,
		lang: 'en',
		dir: null,
		charset: 'utf8',
		baseHref: null,
		viewportRaw: 'width=device-width, initial-scale=1',
		themeColor: null,
		applicationName: null,
		author: null,
		generator: null,
		publisher: null,
		robotsRaw: null,
		noindex: false,
		nofollow: false,
		noarchive: false,
		noimageindex: false,
		googlebot: null,
		canonical: 'https://example.com/',
		amphtml: null,
		manifest: null,
		iconHref: null,
		appleTouchIconHref: null,
		ogType: null,
		ogTitle: 'Example Page',
		ogUrl: null,
		ogSiteName: null,
		ogDescription: null,
		ogImage: null,
		ogImageAlt: null,
		ogImageWidth: null,
		ogImageHeight: null,
		ogLocale: null,
		ogArticlePublishedTime: null,
		ogArticleModifiedTime: null,
		twitterCard: null,
		twitterSite: null,
		twitterCreator: null,
		twitterTitle: null,
		twitterDescription: null,
		twitterImage: null,
		fbAppId: null,
		verificationGoogle: null,
		formatDetectionTelephone: null,
		firstCrawledAt: 1_700_000_000_000,
		lastCrawledAt: 1_700_000_000_000,
		tagCount: null,
		jsonldCount: null,
		tagsProvidersCsv: null,
		mainContentNodeName: 'MAIN',
		mainContentId: null,
		mainContentRole: null,
		mainContentSelector: 'main',
		mainContentClassList: null,
		mainContentWordCount: 500,
		mainContentBodyWordCount: 600,
		mainContentHeadingCount: 3,
		mainContentImageCount: 2,
		mainContentTableCount: 0,
		mainContentButtonCount: 1,
		mainContentIframeCount: 0,
		mainContentVideoCount: 0,
		mainContentAudioCount: 0,
		mainContentCanvasCount: 0,
		scrollHeightDesktop: 1200,
		scrollHeightMobile: 2400,
		templateKey: null,
		metaExtras: {},
		jsonLd: { count: 0, types: [], parseErrorCount: 0 },
		tags: { count: 0, providerIds: {} },
		responseHeaders: {},
		outboundLinks: [],
		redirectFrom: [],
		aliasUrls: [],
		consoleLogs: [],
	};
	return { ...base, ...overrides };
}
