import crypto from 'node:crypto';
import { existsSync } from 'node:fs';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';

import { Archive, CrawlerOrchestrator } from '@nitpicker/crawler';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';

describe('Output path (filePath option)', () => {
	let orchestrator: CrawlerOrchestrator;
	let cwd: string;
	let outputPath: string;

	beforeAll(async () => {
		cwd = path.join(os.tmpdir(), `nitpicker-e2e-output-${crypto.randomUUID()}`);
		await fs.mkdir(cwd, { recursive: true });

		outputPath = path.join(cwd, 'custom-output.nitpicker');

		orchestrator = await CrawlerOrchestrator.crawling(
			['http://localhost:8010/'],
			{
				cwd,
				filePath: outputPath,
				recursive: false,
				image: false,
				interval: 0,
				parallels: 1,
				fetchExternal: false,
			},
			(q) => {
				q.on('error', (e) => {
					console.error('[nitpicker:e2e:output-path] error:', e); // eslint-disable-line no-console
				});
			},
		);
	}, 120_000);

	afterAll(async () => {
		orchestrator?.garbageCollect();
		await fs.rm(cwd, { recursive: true, force: true }).catch(() => {});
	});

	it('指定したパスにアーカイブが書き出される', async () => {
		await orchestrator.write();

		expect(existsSync(outputPath)).toBe(true);
		const stat = await fs.stat(outputPath);
		expect(stat.size).toBeGreaterThan(0);
	});

	it('config.name にファイル名が反映される', async () => {
		const accessor = await Archive.connect(orchestrator.archive.tmpDir);
		const config = await accessor.getConfig();
		expect(config.name).toBe('custom-output');
	});

	it('自動生成のファイルが作成されていない', async () => {
		const files = await fs.readdir(cwd);
		const autoGeneratedFiles = files.filter(
			(f) => f.endsWith('.nitpicker') && f !== 'custom-output.nitpicker',
		);
		expect(autoGeneratedFiles).toHaveLength(0);
	});
});

describe('Output path without extension', () => {
	let orchestrator: CrawlerOrchestrator;
	let cwd: string;

	beforeAll(async () => {
		cwd = path.join(os.tmpdir(), `nitpicker-e2e-output-bare-${crypto.randomUUID()}`);
		await fs.mkdir(cwd, { recursive: true });

		orchestrator = await CrawlerOrchestrator.crawling(
			['http://localhost:8010/'],
			{
				cwd,
				filePath: path.join(cwd, 'my-report'),
				recursive: false,
				image: false,
				interval: 0,
				parallels: 1,
				fetchExternal: false,
			},
			(q) => {
				q.on('error', (e) => {
					console.error('[nitpicker:e2e:output-bare] error:', e); // eslint-disable-line no-console
				});
			},
		);
	}, 120_000);

	afterAll(async () => {
		orchestrator?.garbageCollect();
		await fs.rm(cwd, { recursive: true, force: true }).catch(() => {});
	});

	it('拡張子なしの指定でも .nitpicker が自動付与される', async () => {
		await orchestrator.write();

		const expectedPath = path.join(cwd, 'my-report.nitpicker');
		expect(existsSync(expectedPath)).toBe(true);
		const stat = await fs.stat(expectedPath);
		expect(stat.size).toBeGreaterThan(0);
	});

	it('config.name に拡張子なしのファイル名が反映される', async () => {
		const accessor = await Archive.connect(orchestrator.archive.tmpDir);
		const config = await accessor.getConfig();
		expect(config.name).toBe('my-report');
	});
});
