/**
 * Input parameters for the main-contents analysis worker.
 */
export type Param = {
	/** The page URL being analyzed. */
	url: string;
	/** Raw HTML of the page. */
	html: string;
	/**
	 * Optional CSS selector to override the default main-content detection.
	 * When `null`, the plugin falls back to its built-in selector priority list.
	 */
	mainContentSelector: string | null;
};

/**
 * Aggregated analysis result for a single page's main content area.
 */
export type Result = {
	/** The `<title>` text of the page (trimmed). */
	title: string;
	/**
	 * Metadata about the detected main content element.
	 * `null` when no main content area could be found on the page.
	 */
	main: MainTag | null;
	/**
	 * Total character count of the main content's text (whitespace removed).
	 * Whitespace is stripped so that the count reflects "meaningful" characters
	 * rather than formatting artifacts from the HTML source.
	 */
	wordCount: number;
	/** All headings (h1-h6) found within the main content. */
	headings: Heading[];
	/** All images found within the main content. */
	images: Image[];
	/** All tables found within the main content. */
	tables: Table[];
	/** Reserved for future paragraph-level analysis. Currently always empty. */
	paragraphs: Record<string, never>[];
};

/**
 * Identifying information about the DOM element used as the main content area.
 * Captured so that reports can show which element was selected and why.
 */
export type MainTag = {
	/** Element tag name (e.g. `"MAIN"`, `"DIV"`). */
	nodeName: string;
	/** The element's `id` attribute, or `null` if absent. */
	id: string | null;
	/** CSS class names on the element. */
	classList: string[];
	/** The WAI-ARIA `role` attribute value, or `null` if absent. */
	role: string | null;
	/**
	 * A unique CSS selector for the element, generated by `@medv/finder`.
	 * Useful for reproducing the selection in browser DevTools.
	 */
	selector: string;
};

/**
 * An `<img>` or `<input type="image">` element found in the main content.
 */
export type Image = {
	/** The resolved `src` attribute URL. */
	src: string;
	/** The `alt` attribute value, or `null` if the attribute is missing. */
	alt: string | null;
};

/**
 * A heading element (h1-h6) found within the main content area.
 */
export type Heading = {
	/** Text content of the heading (whitespace-normalized). */
	text: string | null;
	/** Heading level extracted from the tag name. */
	level: HeadingLevel;
};

/** Valid HTML heading levels. */
export type HeadingLevel = 1 | 2 | 3 | 4 | 5 | 6;

/**
 * Structural summary of a `<table>` found within the main content.
 * Provides a quick overview without exposing the full cell data.
 */
export type Table = {
	/** Number of `<tr>` elements in the table. */
	rows: number;
	/** Number of `<th>` + `<td>` in the first row (column count). */
	cols: number;
	/** Whether the table contains a `<thead>` element. */
	hasHeader: boolean;
	/** Whether the table contains a `<tfoot>` element. */
	hasFooter: boolean;
	/** Whether any cell uses `colspan` or `rowspan` attributes. */
	hasMergedCell: boolean;
};
