/**
 * Attributes whose values HTML selectors compare ASCII case-insensitively
 * even without an `i` flag (`input[type=text]` matches `type="TEXT"`),
 * per the HTML Standard's selector rules for HTML elements. The engine
 * applies this by name, without checking the element's namespace.
 * @example
 * CASE_INSENSITIVE_ATTRIBUTE_NAMES.has('type'); // true
 */
export const CASE_INSENSITIVE_ATTRIBUTE_NAMES: ReadonlySet<string> = new Set([
	'accept',
	'accept-charset',
	'align',
	'alink',
	'axis',
	'bgcolor',
	'charset',
	'checked',
	'clear',
	'codetype',
	'color',
	'compact',
	'declare',
	'defer',
	'dir',
	'direction',
	'disabled',
	'enctype',
	'face',
	'frame',
	'hreflang',
	'http-equiv',
	'lang',
	'language',
	'link',
	'media',
	'method',
	'multiple',
	'nohref',
	'noresize',
	'noshade',
	'nowrap',
	'readonly',
	'rel',
	'rev',
	'rules',
	'scope',
	'scrolling',
	'selected',
	'shape',
	'target',
	'text',
	'type',
	'valign',
	'valuetype',
	'vlink',
]);
