import { existsSync } from 'node:fs';
import path from 'node:path';

import { defineConfig, devices } from '@playwright/test';

const dirname = import.meta.dirname;
const stubDir = path.resolve(dirname, 'e2e/.fixture-stub-cwd/._nitpicker-e2e-stub');
const cliBin = path.resolve(dirname, '../cli/bin/nitpicker.js');

/** Port the stub-mode viewer server listens on during E2E. */
const PORT = 4326;

/**
 * Playwright configuration for the **stub-mode** Viewer E2E suite.
 *
 * Sibling of `playwright.config.ts` (the archive-file variant): same SPA,
 * same CLI bin, but the `webServer` points to an in-progress crawl tmpDir
 * (generated by `e2e/generate-stub-fixture.mjs`). The suite asserts the
 * viewer:
 *
 * - starts cleanly against a directory source,
 * - reports `mode: 'stub'` via `/api/info`,
 * - renders the "live crawl snapshot" footer badge, and
 * - leaves the tmpDir intact / does not produce a `.nitpicker` file after
 *   shutdown.
 *
 * Kept in its own config so the two e2e runs can be invoked independently
 * (and so the archive-mode config's fixture wiring stays untouched).
 */
if (!existsSync(stubDir)) {
	throw new Error(
		`Stub fixture not found: ${stubDir}. Run e2e/generate-stub-fixture.mjs first.`,
	);
}

export default defineConfig({
	testDir: './e2e',
	testMatch: /viewer-stub\.spec\.ts$/,
	fullyParallel: false,
	workers: 1,
	retries: 0,
	reporter: 'list',
	webServer: {
		command: `node ${cliBin} viewer ${stubDir} --no-open --port ${PORT}`,
		url: `http://localhost:${PORT}`,
		reuseExistingServer: false,
		timeout: 60_000,
	},
	use: {
		baseURL: `http://localhost:${PORT}`,
		// Pin the browser locale so footer-badge text assertions are
		// deterministic across developer machines / CI runners (the i18n
		// provider derives initial locale from `navigator.language`).
		locale: 'en-US',
		trace: 'on-first-retry',
	},
	projects: [{ name: 'chromium', use: { ...devices['Desktop Chrome'] } }],
});
